#!/usr/bin/env python3
"""
Compare Redis v6 vs v7 command JSON files and generate a diff report.

Reads from v6_commands/ and v7_commands/ directories (generated by generate_command_jsons.py)
and outputs redis_v6_v7_diff.md.
"""

import json
import os
import sys
from pathlib import Path
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
V6_DIR = os.path.join(SCRIPT_DIR, "v6_commands")
V7_DIR = os.path.join(SCRIPT_DIR, "v7_commands")
OUTPUT = os.path.join(SCRIPT_DIR, "redis_v6_v7_diff.md")


def load_commands(directory):
    """Load all command JSON files from a directory. Returns {cmd_name: data}."""
    commands = {}
    for json_file in sorted(Path(directory).glob("*.json")):
        with open(json_file) as f:
            data = json.load(f)
        for cmd_name, cmd_data in data.items():
            commands[cmd_name] = cmd_data
            commands[cmd_name]["_file"] = json_file.name
    return commands


def is_v7_version(ver):
    """Check if a version string is >= 7.0.0."""
    try:
        return int(ver.split(".")[0]) >= 7
    except (ValueError, IndexError, AttributeError):
        return False


def collect_new_v7_args(arguments, depth=0):
    """Recursively find arguments with since >= 7.0.0."""
    results = []
    for arg in arguments:
        if is_v7_version(arg.get("since", "")):
            results.append((depth, arg))
        if "arguments" in arg:
            results.extend(collect_new_v7_args(arg["arguments"], depth + 1))
    return results


def fmt_arg(arg, depth=0):
    """Format a single argument for display."""
    indent = "  " * depth
    parts = [f"{indent}- `{arg['name']}` (type: {arg['type']})"]
    if arg.get("token"):
        parts.append(f"token=`{arg['token']}`")
    if arg.get("optional"):
        parts.append("[optional]")
    if arg.get("multiple"):
        parts.append("[multiple]")
    if arg.get("since"):
        parts.append(f"since {arg['since']}")
    return " ".join(parts)


def fmt_args_tree(arguments, depth=0):
    """Recursively format all arguments."""
    lines = []
    for arg in arguments:
        lines.append(fmt_arg(arg, depth))
        if "arguments" in arg:
            lines.extend(fmt_args_tree(arg["arguments"], depth + 1))
    return lines


def args_to_name_map(arguments):
    """Build a dict of {name: arg} from an argument list."""
    result = {}
    for arg in arguments:
        result[arg.get("name", "")] = arg
    return result


def diff_arguments(v6_args, v7_args, depth=0):
    """Deeply compare argument lists between v6 and v7.

    Returns a list of (depth, change_type, description) tuples.
    change_type: 'added', 'removed', 'changed'
    """
    diffs = []
    v6_map = args_to_name_map(v6_args)
    v7_map = args_to_name_map(v7_args)

    v6_names = list(v6_map.keys())
    v7_names = list(v7_map.keys())

    # Added arguments
    for name in v7_names:
        if name not in v6_map:
            a = v7_map[name]
            since = a.get("since", "")
            desc = f"`{name}` (type: {a.get('type', '?')})"
            if a.get("token"):
                desc += f" token=`{a['token']}`"
            if a.get("optional"):
                desc += " [optional]"
            if since:
                desc += f" since {since}"
            diffs.append((depth, "added", desc))

    # Removed arguments
    for name in v6_names:
        if name not in v7_map:
            a = v6_map[name]
            desc = f"`{name}` (type: {a.get('type', '?')})"
            if a.get("token"):
                desc += f" token=`{a['token']}`"
            diffs.append((depth, "removed", desc))

    # Changed arguments (present in both)
    for name in v6_names:
        if name not in v7_map:
            continue
        a6 = v6_map[name]
        a7 = v7_map[name]
        changes = []

        if a6.get("type") != a7.get("type"):
            changes.append(f"type: `{a6.get('type')}` → `{a7.get('type')}`")
        if a6.get("token") != a7.get("token"):
            changes.append(f"token: `{a6.get('token')}` → `{a7.get('token')}`")
        if a6.get("optional") != a7.get("optional"):
            changes.append(f"optional: {a6.get('optional', False)} → {a7.get('optional', False)}")
        if a6.get("multiple") != a7.get("multiple"):
            changes.append(f"multiple: {a6.get('multiple', False)} → {a7.get('multiple', False)}")
        if a6.get("multiple_token") != a7.get("multiple_token"):
            changes.append(f"multiple_token: {a6.get('multiple_token', False)} → {a7.get('multiple_token', False)}")

        if changes:
            desc = f"`{name}`: " + "; ".join(changes)
            diffs.append((depth, "changed", desc))

        # Recurse into sub-arguments
        sub6 = a6.get("arguments", [])
        sub7 = a7.get("arguments", [])
        if sub6 or sub7:
            sub_diffs = diff_arguments(sub6, sub7, depth + 1)
            if sub_diffs:
                diffs.append((depth, "changed", f"`{name}` sub-arguments:"))
                diffs.extend(sub_diffs)

    return diffs


def fmt_reply_schema_summary(schema):
    """Produce a compact one-line summary of a reply_schema."""
    if schema is None:
        return "*none*"
    if isinstance(schema, dict):
        if "const" in schema:
            return f'const `{schema["const"]}`'
        if "type" in schema:
            t = schema["type"]
            if t == "object" and "properties" in schema:
                props = ", ".join(sorted(schema["properties"].keys()))
                return f"object{{{props}}}"
            if t == "array" and "items" in schema:
                inner = fmt_reply_schema_summary(schema["items"])
                return f"array[{inner}]"
            return str(t)
        if "anyOf" in schema:
            parts = [fmt_reply_schema_summary(s) for s in schema["anyOf"]]
            return " | ".join(parts)
        if "oneOf" in schema:
            parts = [fmt_reply_schema_summary(s) for s in schema["oneOf"]]
            return " | ".join(parts)
    return json.dumps(schema, ensure_ascii=False)[:80]


def diff_reply_schemas(v6_schema, v7_schema):
    """Compare reply_schema between v6 and v7. Returns list of difference strings."""
    if v6_schema == v7_schema:
        return []
    diffs = []
    if v6_schema is None and v7_schema is not None:
        diffs.append(f"Reply schema added in v7: {fmt_reply_schema_summary(v7_schema)}")
    elif v6_schema is not None and v7_schema is None:
        diffs.append(f"Reply schema removed in v7 (was: {fmt_reply_schema_summary(v6_schema)})")
    else:
        diffs.append(f"v6: {fmt_reply_schema_summary(v6_schema)}")
        diffs.append(f"v7: {fmt_reply_schema_summary(v7_schema)}")
    return diffs


def main():
    if not os.path.isdir(V6_DIR) or not os.path.isdir(V7_DIR):
        print(f"ERROR: Run generate_command_jsons.py first to create {V6_DIR} and {V7_DIR}")
        sys.exit(1)

    v6 = load_commands(V6_DIR)
    v7 = load_commands(V7_DIR)

    # Separate into top-level and subcommands for both versions
    v6_top = {n: d for n, d in v6.items() if "|" not in n}
    v6_sub = {n: d for n, d in v6.items() if "|" in n}
    v7_top = {n: d for n, d in v7.items() if "|" not in n}
    v7_sub = {n: d for n, d in v7.items() if "|" in n}

    # For command-level comparison, use all commands (top + sub)
    v6_names = set(v6.keys())
    v7_names = set(v7.keys())
    v7_top_names = set(v7_top.keys())

    out = []
    out.append("# Redis v6.2 → v7.2 Command Differences\n")
    out.append(f"- v6 total: **{len(v6)}** ({len(v6_top)} top-level + {len(v6_sub)} subcommands)")
    out.append(f"- v7 total: **{len(v7)}** ({len(v7_top)} top-level + {len(v7_sub)} subcommands)")
    out.append("")

    # ================================================================
    # 1. New commands in v7 (top-level + subcommands)
    # ================================================================
    out.append("---\n## 1. New Commands in v7\n")
    new_all = sorted(v7_names - v6_names)
    if new_all:
        by_group = defaultdict(list)
        for n in new_all:
            by_group[v7[n].get("group", "other")].append(n)
        for group in sorted(by_group):
            out.append(f"### {group}\n")
            out.append("| Command | Since | Arity | Summary |")
            out.append("|---------|-------|-------|---------|")
            for n in sorted(by_group[group]):
                d = v7[n]
                out.append(f"| `{n}` | {d.get('since','')} | {d.get('arity','')} | {d.get('summary','')} |")
            out.append("")
    else:
        out.append("*None*\n")

    # ================================================================
    # 2. Removed commands (in v6 but not in v7)
    # ================================================================
    out.append("---\n## 2. Removed / Deprecated Commands\n")
    removed = sorted(v6_names - v7_names)
    if removed:
        out.append("| Command | v6 Arity | v6 Flags |")
        out.append("|---------|----------|----------|")
        for n in removed:
            d = v6[n]
            out.append(f"| `{n}` | {d.get('arity','')} | {', '.join(d.get('command_flags',[]))} |")
        out.append("")
    else:
        out.append("*None*\n")

    # ================================================================
    # 3. New subcommands in v7
    # ================================================================
    out.append("---\n## 3. Subcommands in v7\n")
    out.append("v7 restructured many commands into parent + subcommand form.\n")
    # Group subcommands by parent
    parents = defaultdict(list)
    for n, d in sorted(v7_sub.items()):
        parent = n.split("|")[0]
        parents[parent].append((n, d))

    for parent in sorted(parents):
        subs = parents[parent]
        out.append(f"### `{parent}`\n")
        out.append("| Subcommand | Since | Arity | Summary |")
        out.append("|------------|-------|-------|---------|")
        for n, d in sorted(subs):
            marker = " **NEW**" if is_v7_version(d.get("since", "")) else ""
            out.append(f"| `{n}` | {d.get('since','')}{marker} | {d.get('arity','')} | {d.get('summary','')} |")
        out.append("")

    # ================================================================
    # 4. Arity changes
    # ================================================================
    out.append("---\n## 4. Arity Changes\n")
    common = sorted(v6_names & v7_names)
    arity_diffs = []
    for n in common:
        a6 = v6[n].get("arity")
        a7 = v7[n].get("arity")
        if a6 != a7:
            arity_diffs.append((n, a6, a7))
    if arity_diffs:
        out.append("| Command | v6 | v7 | Notes |")
        out.append("|---------|----|----|-------|")
        for n, a6, a7 in arity_diffs:
            note = ""
            if a6 is not None and a7 is not None:
                if a6 > 0 and a7 < 0:
                    note = "Fixed → variable args"
                elif a6 < 0 and a7 > 0:
                    note = "Variable → fixed args"
            out.append(f"| `{n}` | {a6} | {a7} | {note} |")
        out.append("")
    else:
        out.append("*No arity changes.*\n")

    # ================================================================
    # 5. Flag changes
    # ================================================================
    out.append("---\n## 5. Command Flag Changes\n")
    flag_diffs = []
    for n in common:
        f6 = set(v6[n].get("command_flags", []))
        f7 = set(v7[n].get("command_flags", []))
        if f6 != f7:
            flag_diffs.append((n, sorted(f7 - f6), sorted(f6 - f7)))
    if flag_diffs:
        out.append("| Command | Added | Removed |")
        out.append("|---------|-------|---------|")
        for n, added, removed_f in flag_diffs:
            a = ", ".join(added) or "—"
            r = ", ".join(removed_f) or "—"
            out.append(f"| `{n}` | {a} | {r} |")
        out.append("")
    else:
        out.append("*No flag changes.*\n")

    # ================================================================
    # 6. ACL category changes
    # ================================================================
    out.append("---\n## 6. ACL Category Changes\n")
    acl_diffs = []
    for n in common:
        a6 = set(v6[n].get("acl_categories", []))
        a7 = set(v7[n].get("acl_categories", []))
        if a6 != a7:
            acl_diffs.append((n, sorted(a7 - a6), sorted(a6 - a7)))
    if acl_diffs:
        out.append("| Command | Added | Removed |")
        out.append("|---------|-------|---------|")
        for n, added, removed_a in acl_diffs:
            a = ", ".join(added) or "—"
            r = ", ".join(removed_a) or "—"
            out.append(f"| `{n}` | {a} | {r} |")
        out.append("")
    else:
        out.append("*No ACL changes.*\n")

    # ================================================================
    # 7. New arguments (since 7.x) on pre-existing commands
    # ================================================================
    out.append("---\n## 7. New v7 Arguments on Existing Commands\n")
    out.append("Arguments with `since >= 7.0.0` on commands that existed before v7.\n")
    found_any = False
    for n in sorted(v7.keys()):
        d = v7[n]
        if is_v7_version(d.get("since", "")):
            continue  # Entirely new command
        new_args = collect_new_v7_args(d.get("arguments", []))
        if not new_args:
            continue
        found_any = True
        out.append(f"### `{n}`\n")
        # Show history if relevant
        for ver, desc in d.get("history", []):
            if is_v7_version(ver):
                out.append(f"- *{ver}*: {desc}")
        out.append("\nNew arguments:")
        for depth, arg in new_args:
            out.append(fmt_arg(arg, depth))
        out.append("")
    if not found_any:
        out.append("*None*\n")

    # ================================================================
    # 8. Behavioral changes from history
    # ================================================================
    out.append("---\n## 8. Behavioral Changes (from `history` field)\n")
    behavior = []
    for n in sorted(v7.keys()):
        d = v7[n]
        if is_v7_version(d.get("since", "")):
            continue
        v7_hist = [(v, desc) for v, desc in d.get("history", []) if is_v7_version(v)]
        if v7_hist:
            behavior.append((n, v7_hist))
    if behavior:
        for n, hist in behavior:
            out.append(f"- **`{n}`**")
            for ver, desc in hist:
                out.append(f"  - {ver}: {desc}")
        out.append("")
    else:
        out.append("*None*\n")

    # ================================================================
    # 9. Deep Argument Differences (input parameters)
    # ================================================================
    out.append("---\n## 9. Input Parameter (Argument) Differences\n")
    out.append("Deep comparison of argument structure for commands present in both v6 and v7.\n")
    arg_diff_count = 0
    for n in common:
        v6_args = v6[n].get("arguments", [])
        v7_args = v7[n].get("arguments", [])
        if not v6_args and not v7_args:
            continue
        diffs = diff_arguments(v6_args, v7_args)
        if not diffs:
            continue
        arg_diff_count += 1
        out.append(f"### `{n}`\n")
        for depth, change_type, desc in diffs:
            indent = "  " * depth
            if change_type == "added":
                out.append(f"{indent}- **+** {desc}")
            elif change_type == "removed":
                out.append(f"{indent}- **-** {desc}")
            else:
                out.append(f"{indent}- **~** {desc}")
        out.append("")
    if arg_diff_count == 0:
        out.append("*No argument differences found.*\n")

    # ================================================================
    # 10. Reply Schema (Output) Differences
    # ================================================================
    out.append("---\n## 10. Reply Schema (Output) Differences\n")
    out.append("Comparison of `reply_schema` between v6 and v7 for shared commands.\n")
    schema_diff_count = 0
    for n in common:
        v6_schema = v6[n].get("reply_schema")
        v7_schema = v7[n].get("reply_schema")
        if v6_schema is None and v7_schema is None:
            continue
        schema_diffs = diff_reply_schemas(v6_schema, v7_schema)
        if not schema_diffs:
            continue
        schema_diff_count += 1
        out.append(f"### `{n}`\n")
        for line in schema_diffs:
            out.append(f"- {line}")
        out.append("")
    if schema_diff_count == 0:
        out.append("*No reply schema differences found.*\n")

    # ================================================================
    # 11. Deprecated Commands in v7
    # ================================================================
    out.append("---\n## 11. Deprecated Commands in v7\n")
    deprecated = []
    for n in sorted(v7.keys()):
        d = v7[n]
        if d.get("deprecated_since") or d.get("doc_flags"):
            dep_since = d.get("deprecated_since", "")
            replaced = d.get("replaced_by", "")
            deprecated.append((n, dep_since, replaced))
    if deprecated:
        out.append("| Command | Deprecated Since | Replaced By |")
        out.append("|---------|-----------------|-------------|")
        for n, dep_since, replaced in deprecated:
            out.append(f"| `{n}` | {dep_since} | {replaced} |")
        out.append("")
    else:
        out.append("*None*\n")

    # ================================================================
    # 12. Full argument specs (collapsible)
    # ================================================================
    out.append("---\n## 12. Full Argument Specs for Shared Commands\n")
    out.append("<details><summary>Click to expand</summary>\n")
    for n in common:
        d = v7[n]
        args = d.get("arguments", [])
        if not args:
            continue
        out.append(f"### `{n}`\n")
        out.append(f"v6 arity: `{v6[n].get('arity')}` → v7 arity: `{d.get('arity')}`  ")
        out.append(f"Group: {d.get('group','')} | Since: {d.get('since','')}  ")
        out.append(f"Summary: {d.get('summary','')}\n")
        out.append("Arguments:")
        out.extend(fmt_args_tree(args))
        out.append("")
    out.append("</details>\n")

    # ================================================================
    # Summary
    # ================================================================
    out.append("---\n## Summary\n")
    out.append("| Metric | Count |")
    out.append("|--------|-------|")
    out.append(f"| v6 commands (top + sub) | {len(v6)} |")
    out.append(f"| v7 commands (top + sub) | {len(v7)} |")
    out.append(f"| New in v7 | {len(new_all)} |")
    out.append(f"| Removed from v6 | {len(removed)} |")
    out.append(f"| Arity changes | {len(arity_diffs)} |")
    out.append(f"| Flag changes | {len(flag_diffs)} |")
    out.append(f"| ACL category changes | {len(acl_diffs)} |")
    out.append(f"| Commands with new v7 args | {sum(1 for n in v7 if not is_v7_version(v7[n].get('since','')) and collect_new_v7_args(v7[n].get('arguments',[])))} |")
    out.append(f"| Behavioral changes | {len(behavior)} |")
    out.append(f"| Argument structure diffs | {arg_diff_count} |")
    out.append(f"| Reply schema diffs | {schema_diff_count} |")
    out.append(f"| Deprecated commands | {len(deprecated)} |")
    out.append("")

    report = "\n".join(out)
    with open(OUTPUT, "w") as f:
        f.write(report)
    print(f"Report written to {OUTPUT}")
    print(f"\nQuick stats:")
    print(f"  New commands:      {len(new_all)}")
    print(f"  Removed:           {len(removed)}")
    print(f"  Arity changes:     {len(arity_diffs)}")
    print(f"  Flag changes:      {len(flag_diffs)}")
    print(f"  ACL changes:       {len(acl_diffs)}")
    print(f"  Arg struct diffs:  {arg_diff_count}")
    print(f"  Reply schema diffs:{schema_diff_count}")
    print(f"  Deprecated:        {len(deprecated)}")


if __name__ == "__main__":
    main()
